#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1551518290                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.kakimov.mooltik
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png
app_name                                  : Mooltik
app_price                                 : Free
app_description                           : Animation studio in your pocket.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Rustem Kakimov
your_link                                 : https://kakimov.dev
# your_city                                 : Copenhagen                                
email_address                             : kakimov.dev@gmail.com
# facebook_username                         :                                           
# instagram_username                        : ebaehr
# twitter_username                          : ebaehr
github_username                           : ruskakimov
# youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Reliable Drawing Tools
    description                           : Quickly switch between 3 brushes of your choice. Scale, stretch, and squish drawings with a lasso tool.
    fontawesome_icon_name                 : paint-brush

  - title                                 : Powerful Timeline
    description                           : Multiple independent frame tracks with different loop modes. Creating complex scenes is simple with Mooltik.
    fontawesome_icon_name                 : stream

  - title                                 : Video Export
    description                           : Export a compressed MP4 file that's ready to be uploaded to your Youtube channel.
    fontawesome_icon_name                 : video
    
  - title                                 : Scene Annotation
    description                           : Jot down your ideas before you have forgotten them. Describe camera movement or what sound effects you will add in the future.
    fontawesome_icon_name                 : edit
  
  - title                                 : Image Import
    description                           : Use any image as a background, or briefly display a meme to entertain your audience.
    fontawesome_icon_name                 : images

  - title                                 : Sound Import
    description                           : Sync the animation to your favourite soundtrack or a recorded voiceover.
    fontawesome_icon_name                 : music



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#424242"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#212121"

link_color                                : "#ffc107"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#757575"

feature_icons_foreground_color            : "#ffc107"
feature_icons_background_color            : "#ffc1071a"

social_icons_foreground_color             : "#ffc107"
social_icons_background_color             : "#ffc1071a"

footer_text_color                         : "#ffffff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
